---
# Changes here will be overwritten by Copier
_commit: v1.4.2
_src_path: gh:remerge/template
deploy_branch: production
google_cloud_gke_master_subnet: null
google_cloud_project: ansible-role-scaleft-[random_id]
google_cloud_region: europe-west4
google_cloud_zone: europe-west4-a
project_description: Install and configure ScaleFT agent with Ansible.
project_id: ansible-role-scaleft
project_license: apache-2.0
project_name: Ansible Role for ScaleFT
project_owner: sre
project_type: ansible-role
use_ansible: false
use_docker: false
use_golang: false
use_google_cloud_compute: false
use_google_cloud_gke: false
use_python: true
use_terraform: false
use_terraform_google: false
