[project]
name = "ansible-role-scaleft"
version = "0.0.0"
description = "Ansible Role for ScaleFT"
authors = [{ name = "Remerge GmbH", email = "core@remerge.io" }]
requires-python = ">=3.14,<3.15"
readme = "README.md"
dependencies = [
]

[dependency-groups]
dev = [
    "ruff==0.15.22",
    "ansible-lint==26.6.0 ; platform_system != 'Windows'",
    "ansible-dev-tools==26.7.1",
]
test = [
    "pytest==9.1.1",
]

[tool.uv]
package = false
default-groups = [
    "dev",
    "test",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
